FROM ubuntu:bionic
MAINTAINER Rich Rose <askrichardrose@gmail.com>

# install XPRA
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl && \
  curl https://winswitch.org/gpg.asc | apt-key add - && \
  echo "deb http://winswitch.org/ bionic main" > /etc/apt/sources.list.d/xpra.list && \
  add-apt-repository universe  > /dev/null 2>&1 && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y xpra xvfb xterm && \
  apt-get clean && \ 
  rm -rf /var/lib/apt/lists/*

# Add xpra tester account
RUN groupadd -r tester && useradd -r -g tester -G audio,video tester \
    && mkdir -p /home/tester/Downloads && chown -R tester:tester /home/tester

######## SAMPLE APPLICATION ##################
# Microsoft's VS Code
RUN apt-get update && apt-get install -y curl && apt-get clean && \
     curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg \
  && install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/ \
  && sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list' \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y apt-transport-https \
  && apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y code

# VSCODE
ADD vscode.sh /usr/local/bin/vscode
RUN chmod +x /usr/local/bin/vscode
######## SAMPLE APPLICATION ##################

# Define User Account
USER tester

ENV DISPLAY=:100

VOLUME /data

WORKDIR /data

# Container Port
EXPOSE 10000

# CMD to execute
CMD xpra start --bind-tcp=0.0.0.0:10000 --html=on --exit-with-children --daemon=no --xvfb="/usr/bin/Xvfb +extension  Composite -screen 0 1920x1080x24+32 -nolisten tcp -noreset" --pulseaudio=no --notifications=no --bell=no --start-child=vscode
